title = "Cubic"

[cayley]
name = "Cayley"
thumbnail = "textures/thumbs/cubic/cayley.png"
bounds_radius = 1.5
raymarch_steps = 120
camera_distance = 7
colormap_scale = 1.5
expression = "-5*[x^2*(y+z)+y^2*(x+z)+z^2*(x+y)]+2*(x*y+x*z+y*z)"

[chmutov_cubic]
name = "Chmutov Cubic"
thumbnail = "textures/thumbs/cubic/chmutov.png"
bounds_shape = 1
bounds_radius = 1.4
raymarch_steps = 60
camera_distance = 10
colormap_scale = 0.75
code_global = '''
float T_3(float x) {
  float x2=x*x;
  return x*(4.*x2-3.);
}
'''
comment = '''
,\\&\mathrm{where}\; T_3(x)=4x^3-3x+1\\
&\mathrm{is\;the\;Chebyshev\;polynomial\;of\;the\;first\;kind\;of\;degree\;3.}
'''
expression = "T_3(x)+T_3(y)+T_3(z)+1"

[clebsch]
name = "Clebsch"
thumbnail = "textures/thumbs/cubic/clebsch.png"
bounds_radius = 1.5
raymarch_steps = 230
camera_distance = 7
colormap_scale = 0.03
expression = '''
81*(x^3+y^3+z^3)-189*(x^2*y+x^2*z+x*y^2+x*z^2+y^2*z+y*z^2)+
54*x*y*z+126*(x*y+x*z+y*z)-9*(x^2+y^2+z^2)-\n9*(x+y+z)+1'''

[ding_dong]
name = "Ding-Dong"
thumbnail = "textures/thumbs/cubic/ding-dong.png"
bounds_radius = 2
raymarch_steps = 50
camera_distance = 9
colormap_scale = 5
expression = "x^2+y^2-(1-z)*z^2"

[strophoid]
name = "Strophoid"
thumbnail = "textures/thumbs/cubic/strophoid.png"
bounds_radius = 1.5
raymarch_steps = 50
camera_distance = 7
colormap_scale = 10
parameters = [{name = "a", value = 1},
              {name = "b", value = -0.1},
              {name = "c", value = 1.5}]
expression = "(b-x)*(y^2+z^2)-c^2*a*x^2-c^2*x^3"