title = "Sextic"

[barth_sextic]
name = "Barth Sextic"
thumbnail = "textures/thumbs/sextic/barth.png"
bounds_radius = 3
raymarch_steps = 200
camera_distance = 14
colormap_scale = 0.45
code_global = "const float phi=1.618033988;"
comment = '''
,\\&\mathrm{where}\; \phi=(1+\sqrt{5})/2\;\mathrm{\;is\;the\;golden\;ratio.}'''
expression = '''
4*(phi^2*x^2-y^2)*(phi^2*y^2-z^2)*(phi^2*z^2-x^2)-
(1+2*phi)*(x^2+y^2+z^2-1)^2'''

[chmutov_sextic]
name = "Chmutov Sextic"
thumbnail = "textures/thumbs/sextic/chmutov.png"
bounds_radius = 2
raymarch_steps = 200
camera_distance = 8
colormap_scale = 1.2
code_global = '''
float T_6(float x) {
  float x2=x*x;
  float a=3.-4.*x2;
  return 2.*x2*a*a-1.;
}
'''
comment = '''
,\\&\mathrm{where}\; T_6(x)=32x^6-48x^4+18x^2-1\\
&\mathrm{is\;the\;Chebyshev\;polynomial\;of\;the\;first\;kind\;of\;degree\;6.}'''
expression = "T_6(x)+T_6(y)+T_6(z)"

[heart]
name = "Heart"
thumbnail = "textures/thumbs/sextic/heart.png"
bounds_radius = 1.6
raymarch_steps = 200
camera_distance = 7
colormap_scale = 10
expression = "(x^2+(9/4)*y^2+z^2-1)^3-x^2*z^3-(9/80)*y^2*z^3"

[high_silhouette]
name = "High Silhouette"
thumbnail = "textures/thumbs/sextic/high_silhouette.png"
bounds_radius = 2
raymarch_steps = 140
raymarch_root_test = 1
camera_distance = 10
colormap_scale = 20
expression = "x^6-y^5-2*x^3*y+y^2"

[hunt]
name = "Hunt"
thumbnail = "textures/thumbs/sextic/hunt.png"
bounds_radius = 4
raymarch_steps = 700
camera_distance = 18
colormap_scale = 0.001
expression = "4*(x^2+y^2+z^2-13)^3+27*(3*x^2+y^2-4*z^2-12)^2"

[kleine]
name = "Kleine"
thumbnail = "textures/thumbs/sextic/kleine.png"
bounds_radius = 3.3
raymarch_steps = 500
camera_distance = 15
colormap_scale = 0.25
expression = '''
(x^2+y^2+z^2+2*y-1)*(x^2+y^2+z^2-2*y-1)^2-8*z^2+
16*x*z*(x^2+y^2+z^2-2*y-1)'''